name: GitHub super linter

# Controls when the action will run. 
on:
  workflow_call:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Only run job when pr is ready-for-review
    if: github.event.pull_request.draft == false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false # Validate new or changed files only
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}
          # Languages and file-extensions
          # To validate further languages: https://github.com/github/super-linter#environment-variables
          VALIDATE_PHP_BUILTIN: true
